export const TASK_GROUPING_BY_FIELDS_LABEL = ['DUE DATE', 'STATUS'];


export const TASK_GROUPING_LABLE_TO_FIELDS_MAP = new Map();
TASK_GROUPING_LABLE_TO_FIELDS_MAP.set('DUE DATE', 'dueDate');
TASK_GROUPING_LABLE_TO_FIELDS_MAP.set('STATUS', 'status');